# Generated by Django 3.0.6 on 2020-05-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('instructions', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.ManyToManyField(related_name='plans_by_age_group', to='materials.AgeGroup')),
                ('category', models.ManyToManyField(related_name='plans_by_category', to='materials.Category')),
                ('level', models.ManyToManyField(related_name='plans_by_level', to='materials.Level')),
            ],
        ),
    ]
