# Generated by Django 3.0.6 on 2020-05-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='instructions',
            field=models.TextField(),
        ),
    ]
