# Generated by Django 3.0.6 on 2020-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_lessonplan_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='sample_images/eedacca0-99c3-11ea-a094-48a472e1fd8d'),
        ),
    ]
