# Generated by Django 3.0.6 on 2020-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20200519_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='sample_image',
            field=models.ImageField(blank=True, null=True, upload_to='sample_images/<function create_filename at 0x0000025D2BADE5E0>'),
        ),
    ]
