# Generated by Django 3.0.6 on 2020-05-19 14:56

from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20200519_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='materials_file',
            field=models.FileField(blank=True, null=True, upload_to=materials.models.create_filename),
        ),
    ]
