# Generated by Django 3.0.6 on 2020-05-27 16:31

from django.conf import settings
from django.db import migrations, models
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0007_lessonplan_materials_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=materials.models.create_filename)),
            ],
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='permitted_user',
            field=models.ManyToManyField(related_name='purchased_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='materials_file',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='materials_file',
            field=models.ManyToManyField(to='materials.MaterialsFile'),
        ),
    ]
