# Generated by Django 3.0.6 on 2020-05-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_materialsfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='materials_file',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='materials_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.MaterialsFile'),
        ),
    ]
