# Generated by Django 3.0.6 on 2020-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20200528_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
