# Generated by Django 3.0.6 on 2020-06-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
