# Generated by Django 3.0.6 on 2020-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0017_order_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'not open'), ('AP', 'awaiting payment'), ('PS', 'payment succeeded'), ('PF', 'payment failed')], default=None, max_length=5, null=True),
        ),
    ]
